// let userNames: string[];
// let userIds:number[];
var userNames;
userNames = ['Akash', 'Fahim', "Rakib"];
// console.log(userNames[1]);
var multipleTypeArray = ['Akash', 'Fahim', "Rakib", 1];
var multipleTypeArray1 = ['Akash', 'Fahim', "Rakib", 1];
userNames.sort();
console.log(userNames);
userNames.push('Heeme');
console.log(userNames);
userNames.pop();
userNames.unshift("milton");
console.log(userNames);
userNames.shift();
userNames.shift();
console.log(userNames);
